#!/usr/bin/env python3

# Standard library imports
from random import randint, choice as rc

# Remote library imports
from faker import Faker

# Local imports
from app import app
from models import db
from models import User,Event,SavedEvent,SignUp


with app.app_context():
    Event.query.delete()
    User.query.delete()
    SavedEvent.query.delete()
    SignUp.query.delete()


    user1= User(id=1,first_name='Stephan',last_name='Rothstein',type='customer')
    user2= User(id=2,first_name='Dylan', last_name='Agosto',type='customer')
    user3= User(id=3,first_name='Jessica', last_name='Smith',type='customer')
    user4= User(id=4,first_name='Daniel', last_name='Dean',type='customer')
    user5= User(id=5,first_name='Alice', last_name='Luster',type='customer')
    user6= User(id=6,first_name='Megan', last_name='Anne',type='customer')
    user7= User(id=7,first_name='Matthew', last_name='John',type='customer')
    user8= User(id=8,first_name='Jaster', last_name='Leon',type='customer')
    user9= User(id=9,first_name='Jennifer', last_name='Coffee',type='customer')
    user10= User(id=10,first_name='Lilly', last_name='Cummings',type='customer')
    user11= User(id=11,first_name='Mark', last_name='Scott',type='customer')
    user12= User(id=12,first_name='Kimberly', last_name='Rey',type='customer')
    user13= User(id=13,first_name='Regina', last_name='Harris',type='customer')
    user14= User(id=14,first_name='Julia', last_name='Jennings',type='customer')
    user15= User(id=15,first_name='Henry', last_name='Burlington',type='customer')
    user16= User(id=16,first_name='Sarah', last_name='Montgomery',type='customer')
    user17= User(id=17,first_name='Rachel', last_name='Sommers',type='customer')
    user18= User(id=18,first_name='Alexander', last_name='Ryans',type='customer')
    user19= User(id=19,first_name='Ernesto', last_name='Cains',type='customer')
    user20= User(id=20,first_name='Justin', last_name='Munster',type='customer')
    user21= User(id=21,first_name='Harry', last_name='Peters',type='customer')
    user22= User(id=22,first_name='Vanessa', last_name='Santos',type='customer')
    user23= User(id=23,first_name='Margo', last_name='Lyons',type='customer')
    user24= User(id=24,first_name='Anthony', last_name='Freeman',type='customer')
    user25= User(id=25,first_name='Lindsay', last_name='Grotto',type='customer')

    event1= Event(id=1,title='Health Tech Startup Networking Rooftop Happy Hour',description='On Wednesday,  January 15, 2025 · 5:30 - 8pm EST, join us for a fun evening of networking with fellow health tech startup enthusiasts on a rooftop with drinks and good vibes! At 230 Fifth Rooftop Bar, 1150 Broadway New York, NY 10001',image='/images/HealthTechStartup.png',location='Manhattan')
    event2= Event(id=2,title='Tech Networking New York',description='On Thursday, December 5 · 6 - 9pm EST, we are hosting an in-person event for participants from the Business industry . We look forward to seeing you at our event. At Whiskey Cellar NYC 77 East 7th Street New York, NY 10003',image='/images/TechNetworkingEventNYC.png',location='Manhattan')
    event3= Event(id=3,title='TECHSPO',description='On May 16th and 17th, part of DigiMarCon East, TECHSPO New York is a two-day trade show and expo aimed at gathering the top developers, marketers, designers, and innovators to reveal the latest trends in the technology sector. At 60 Furman St, Brooklyn NY, 11201',image='/images/TECHSPO.png',location='Brooklyn')
    event4= Event(id=4,title='Tech Up For Women Conference NYC',description='On Tuesday, May 6, a one day conference event to advance through technology knowledge. The program offers a fast moving event to embrace technology. At 639 W 46th St, New York, NY 10036 First Floor Event Hall New York, NY 10001',image='/images/TechUpForWomen.png',location='Manhattan')
    event5= Event(id=5,title='Flushing Tech Meetup - Hackathon at TIQC',description='On December 14th and December 28th, get ready to dive into the world of innovation and collaboration at the Tech Incubator at Queens College, where the Flushing Tech Meetup is hosting an electrifying hackathon just for you. At 6530 Kissena Blvd, Flushing, NY 11367',image='/images/FlushingTechMeetup.png',location='Queens')
    event6= Event(id=6,title='Bronx Ed Tech Showcase',description='Please join us for the 11th Annual Bronx Ed Tech Showcase, Friday May 3rd at Hostos Community College! The theme of this year is: Let’s Talk: Rethinking Authentic Learning & Assessment in the Age of AI. At 500 Grand Concourse, Bronx, NY, 10451',image='/images/BronxTechEdShowcase.png',location='Bronx')
    event7= Event(id=7,title='Tech Talk Time',description='On Dec 11 2024 11:00am - 11:30am, join us for “Tech Talk Time,” where you can ask your technology-related questions and get assistance. Don’t miss out on this opportunity to enhance your tech skills!, at 2800 Victory Blvd Staten Island, NY 10314',image='/images/TechTalkTime.png',location='Staten Island')
    event8= Event(id=8,title='NYC Tech Toastmasters',description='Join us on Wednesday, December 18th, 2024 at 6:45 PM EST for an evening of networking and public speaking practice.From impromptu speeches to prepared presentations, our meetings offer diverse opportunities to step out of your comfort zone and into the spotlight. At 232 East 9th Street ## 1 New York, NY 10003',image='/images/NYCTechToastmasters.png',location='Manhattan')
    event9= Event(id=9,title='NYC Tech & AI Social Event',description='On Wednesday, December 4 · 6 - 8:30pm EST,Connect over drinks in SoHo with dynamic professionals in tech, This is an ideal opportunity for founders, entrepreneurs, and students to come together, learn, and share experiences. discussing trends and ideas at 136 Crosby St 4th floor, 10012.',image='/images/NYCTechAndAISocialEvent.png',location='Manhattan')
    event10= Event(id=10,title='Tech Networking New York Brooklyn',description='On Wednesday, December 11 · 6 - 9pm EST, we are hosting a unique opportunity to connect with top entrepreneurs and venture capitalists, exchange ideas, and grow your business network. At 143 Troutman Street Brooklyn, NY 11206',image='/images/TechNetworkingNewYorkBrooklyn.png',location='Brooklyn')
    event11= Event(id=11,title='Tech and Startup Networking Mixer',description='On Thursday, Janurary 2nd at 5pm, NYCs largest and best networking mixer in the startup space is back. We call all tech founders, SaaS founders, entrepreneurs, recruiters, freelancers, startup mentors, coaches, and engineers for an evening of great connections and networking. At 110 Delancey Street New York, NY 10002',image='/images/TechAndStartupNetworkingMixer.png',location='Manhattan')
    event12= Event(id=12,title='Astoria Hacking Club',description='Are you a hacker living in Astoria? Do you wish we had a Wonderville or a hackerspace nearby? Look no further, we’re gathering weekly at Heart of Gold on Tuesdays at 6 PM. This event will take place at Heart of Gold 37-14 31st Avenue,Astoria, NY 11103',image='/images/AstoriaHackingClub.png',location='Queens')
    event13= Event(id=13,title='NY Tech Meetup',description='This months NY Tech Meetup will be taking place on Monday, December 9 at Civic Hall Union Square! Its the world’s largest meetup group of its kind with members who have a common interest in learning from and helping one another. At 124 E 14th St, New York, NY 10003 United States',image='/images/NYTechAlliance.png',location='Manhattan')
    event14= Event(id=14,title='New York Tech & Finance Networking Event',description='On Wednesday December 4th, Embark on an exhilarating journey into the Future of Technology and Finance, where innovation meets investment and startups thrive! At he Crown, 50 Bowery New York, NY 10013',image='/images/TechAndFinanceNetworking.png',location='Manhattan')
    event15= Event(id=15,title='Tech Soup Roadshow',description='On December 3rd from 10am-4pm, You will see our LED solutions on display as well as learn more about all the ingredients that make up our "Tech Soup" via mounting, rigging, content, and processor partners to create the best solution for your digital display needs. At 307 W 38th St studio 1201, 12th floor',image='/images/TechSoupRoadshow.png',location='Manhattan')
    event16=Event(id=16,title='NYC Women In Tech Meetup',description='On December 7th from 1-2 pm, toasts member meetups are the opposite of your usual tech meetup! Connect with women and non-binary folks in tech who meet you where you are. At419 East 74th Street New York, NY 10021',image='/images/NYCWomenInTechMeetUp.png',location='Manhattan')
    event17=Event(id=17,title='Tech and Business Networking | Elevating Your Potential - NYC',description='On Wednesday, December 11 · 6 - 8pm EST, meet Consultants, Analysts of all types, Bankers, Software Engineers, Entrepreneurs, and more who are active in the space or are eager to get started. At Jack Doyles: 240 West 35th Street New York, NY 10001',image='TechAndBussinessNetowrking.png',location='Manhattan')
    event18=Event(id=18,title='Women in Tech New York 2025',description='On Thursday, May 22, 2025 · 6 - 9pm EDT, calling all women in tech! Join us for an exclusive networking event as part of the Women in Tech Global Conference 2025, in the dynamic city of New York. This is your opportunity to connect with fellow women in the tech industry, share experiences, and build valuable professional relationships in a supportive and empowering environment.',image='/images/WomenInTechGlobalConference.png',location='Manhattan')
    event19=Event(id=19,title='Cyber Tech NYC',description='On September 4th, Cybertech conferences are the go-to place to create new business, cultivate futures, nurture connections, and learn about the latest technology innovations and solutions to challenges present in the current Cyber Era. At the Metropolitan Pavillion, Chelsea: 125 West 18th Street, New York, NY 10011',image='/images/CyberTechNYC2025.png',location='Manhattan')
    event20=Event(id=20,title='Tech, Real Estate, Fashion, Marketing Networking',description='On Thursday, December 12 · 6 - 8pm EST, come join us for a night of networking and collaboration at the Sandbar Rooftop! This event is the perfect opportunity for professionals in the tech, real estate, fashion, and marketing industries to connect and share ideas. At 152 West 26th Street New York, NY 10001',image='/images/TechMarketingRealEstateFashion.png',location='Manhattan')

    signup1=SignUp(id=1, attending_event='Yes', user_id=1, event_id=20)
    signup2=SignUp(id=2, attending_event='Yes', user_id=1, event_id=19)
    signup3=SignUp(id=3, attending_event='Yes', user_id=2, event_id=17)
    signup4=SignUp(id=4, attending_event='Yes', user_id=2, event_id=15)
    signup5=SignUp(id=5, attending_event='Yes', user_id=3, event_id=4)
    signup6=SignUp(id=6, attending_event='Yes', user_id=3, event_id=18)
    signup7=SignUp(id=7, attending_event='Yes', user_id=4, event_id=19)
    signup8=SignUp(id=8, attending_event='Yes', user_id=4, event_id=12)
    signup9=SignUp(id=9, attending_event='Yes', user_id=5, event_id=4)
    signup10=SignUp(id=10, attending_event='Yes', user_id=5, event_id=12)
    signup11=SignUp(id=11, attending_event='Yes', user_id=6, event_id=8)
    signup12=SignUp(id=12, attending_event='Yes', user_id=6, event_id=1)
    signup13=SignUp(id=13, attending_event='Yes', user_id=7, event_id=14)
    signup14=SignUp(id=14, attending_event='Yes', user_id=7, event_id=20)
    signup15=SignUp(id=15, attending_event='Yes', user_id=8, event_id=15)
    signup16=SignUp(id=16, attending_event='Yes', user_id=8, event_id=20)
    signup17=SignUp(id=17, attending_event='Yes', user_id=9, event_id=7)
    signup18=SignUp(id=18, attending_event='Yes', user_id=9, event_id=18)
    signup19=SignUp(id=19, attending_event='Yes', user_id=10, event_id=15)
    signup20=SignUp(id=20, attending_event='Yes', user_id=10, event_id=6)
    signup21=SignUp(id=21, attending_event='Yes', user_id=11, event_id=11)
    signup22=SignUp(id=22, attending_event='Yes', user_id=11, event_id=20)
    signup23=SignUp(id=23, attending_event='Yes', user_id=12, event_id=14)
    signup24=SignUp(id=24, attending_event='Yes', user_id=12, event_id=13)
    signup25=SignUp(id=25, attending_event='Yes', user_id=13, event_id=16)
    signup26=SignUp(id=26, attending_event='Yes', user_id=13, event_id=13)
    signup27=SignUp(id=27, attending_event='Yes', user_id=14, event_id=3)
    signup28=SignUp(id=28, attending_event='Yes', user_id=14, event_id=6)
    signup29=SignUp(id=29, attending_event='Yes', user_id=15, event_id=7)
    signup30=SignUp(id=30, attending_event='Yes', user_id=15, event_id=8)
    signup31=SignUp(id=31, attending_event='Yes', user_id=16, event_id=9)
    signup32=SignUp(id=32, attending_event='Yes', user_id=16, event_id=19)
    signup33=SignUp(id=33, attending_event='Yes', user_id=17, event_id=18)
    signup34=SignUp(id=34, attending_event='Yes', user_id=17, event_id=15)
    signup35=SignUp(id=35, attending_event='Yes', user_id=18, event_id=20)
    signup36=SignUp(id=36, attending_event='Yes', user_id=18, event_id=1)
    signup37=SignUp(id=37, attending_event='Yes', user_id=19, event_id=19)
    signup38=SignUp(id=38, attending_event='Yes', user_id=19, event_id=1)
    signup39=SignUp(id=39, attending_event='Yes', user_id=20, event_id=12)
    signup40=SignUp(id=40, attending_event='Yes', user_id=20, event_id=10)
    signup41=SignUp(id=41, attending_event='Yes', user_id=21, event_id=11)
    signup42=SignUp(id=42, attending_event='Yes', user_id=21, event_id=12)
    signup43=SignUp(id=43, attending_event='Yes', user_id=22, event_id=13)
    signup44=SignUp(id=44, attending_event='Yes', user_id=22, event_id=16)
    signup45=SignUp(id=45, attending_event='Yes', user_id=23, event_id=14)
    signup46=SignUp(id=46, attending_event='Yes', user_id=23, event_id=7)
    signup47=SignUp(id=47, attending_event='Yes', user_id=24, event_id=1)
    signup48=SignUp(id=48, attending_event='Yes', user_id=24, event_id=20)
    signup49=SignUp(id=49, attending_event='Yes', user_id=25, event_id=19)
    signup50=SignUp(id=50, attending_event='Yes', user_id=25, event_id=7)

    savedevent1=SavedEvent(id=1, user_id=1, event_id=1)
    savedevent2=SavedEvent(id=2, user_id=1, event_id=2)
    savedevent3=SavedEvent(id=3, user_id=2, event_id=3)
    savedevent4=SavedEvent(id=4, user_id=2, event_id=5)
    savedevent5=SavedEvent(id=5, user_id=3, event_id=9)
    savedevent6=SavedEvent(id=6, user_id=3, event_id=8)
    savedevent7=SavedEvent(id=7, user_id=4, event_id=5)
    savedevent8=SavedEvent(id=8, user_id=4, event_id=9)
    savedevent9=SavedEvent(id=9, user_id=5, event_id=1)
    savedevent10=SavedEvent(id=10, user_id=5, event_id=6)
    savedevent11=SavedEvent(id=11, user_id=6, event_id=7)
    savedevent12=SavedEvent(id=12, user_id=6, event_id=19)
    savedevent13=SavedEvent(id=13, user_id=7, event_id=5)
    savedevent14=SavedEvent(id=14, user_id=7, event_id=3)
    savedevent15=SavedEvent(id=15, user_id=8, event_id=17)
    savedevent16=SavedEvent(id=16, user_id=8, event_id=14)
    savedevent17=SavedEvent(id=17, user_id=9, event_id=5)
    savedevent18=SavedEvent(id=18, user_id=9, event_id=8)
    savedevent19=SavedEvent(id=19, user_id=10, event_id=12)
    savedevent20=SavedEvent(id=20, user_id=10, event_id=9)
    savedevent21=SavedEvent(id=21, user_id=11, event_id=7)
    savedevent22=SavedEvent(id=22, user_id=11, event_id=6)
    savedevent23=SavedEvent(id=23,user_id=12, event_id=16)
    savedevent24=SavedEvent(id=24, user_id=12, event_id=2)
    savedevent25=SavedEvent(id=25, user_id=13, event_id=8)
    savedevent26=SavedEvent(id=26, user_id=13, event_id=5)
    savedevent27=SavedEvent(id=27, user_id=14, event_id=3)
    savedevent28=SavedEvent(id=28, user_id=14, event_id=18)
    savedevent29=SavedEvent(id=29, user_id=15, event_id=10)
    savedevent30=SavedEvent(id=30, user_id=15, event_id=11)
    savedevent31=SavedEvent(id=31, user_id=16, event_id=7)
    savedevent32=SavedEvent(id=32, user_id=16, event_id=4)
    savedevent33=SavedEvent(id=33, user_id=17, event_id=9)
    savedevent34=SavedEvent(id=34, user_id=17, event_id=15)
    savedevent35=SavedEvent(id=35, user_id=18, event_id=3)
    savedevent36=SavedEvent(id=36, user_id=18, event_id=2)
    savedevent37=SavedEvent(id=37, user_id=19, event_id=15)
    savedevent38=SavedEvent(id=38, user_id=19, event_id=17)
    savedevent39=SavedEvent(id=39, user_id=20, event_id=1)
    savedevent40=SavedEvent(id=40, user_id=20, event_id=20)
    savedevent41=SavedEvent(id=41, user_id=21, event_id=1)
    savedevent42=SavedEvent(id=42, user_id=21, event_id=9)
    savedevent43=SavedEvent(id=43, user_id=22, event_id=10)
    savedevent44=SavedEvent(id=44, user_id=22, event_id=4)
    savedevent45=SavedEvent(id=45, user_id=23, event_id=3)
    savedevent46=SavedEvent(id=46, user_id=23, event_id=6)
    savedevent47=SavedEvent(id=47, user_id=24, event_id=13)
    savedevent48=SavedEvent(id=48, user_id=24, event_id=2)
    savedevent49=SavedEvent(id=49, user_id=25, event_id=15)
    savedevent50=SavedEvent(id=50, user_id=25, event_id=18)



    db.session.add_all([user1,user2,user3,user4,user5,user6,user7,user8,user9,user10,user11,user12,user13,user14,user15,user16,user17,user18,user19,user20,user21,user22,user23,user24,user25])
    db.session.add_all([event1,event2,event3,event4,event5,event6,event7,event8,event9,event10,event11,event12,event13,event14,event15,event16,event17,event18,event19,event20])
    db.session.add_all([signup1,signup2,signup3,signup4,signup5,signup6,signup7,signup8,signup9,signup10,signup11,signup12,signup13,signup14,signup15,signup16,signup17,signup18,signup19,signup20,signup21,signup22,signup23,signup24,signup25,signup26,signup27,signup28,signup29,signup30,signup31,signup32,signup33,signup34,signup35,signup36,signup37,signup38,signup39,signup40,signup41,signup42,signup43,signup44,signup45,signup46,signup47,signup48,signup49,signup50])
    db.session.add_all([savedevent1,savedevent2,savedevent3,savedevent4,savedevent5,savedevent6,savedevent7,savedevent8,savedevent9,savedevent10,savedevent11,savedevent12,savedevent13,savedevent14,savedevent15,savedevent16,savedevent17,savedevent18,savedevent19,savedevent20,savedevent21,savedevent22,savedevent23,savedevent24,savedevent25,savedevent26,savedevent27,savedevent28,savedevent29,savedevent30,savedevent31,savedevent32,savedevent33,savedevent34,savedevent35,savedevent36,savedevent37,savedevent38,savedevent39,savedevent40,savedevent41,savedevent42,savedevent43,savedevent44,savedevent45,savedevent46,savedevent47,savedevent48,savedevent49,savedevent50])
    db.session.commit()

    print("🌱 Events, Users, Sign ups, and Saved events successfully seeded 🌱")


